apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: taskmanager-deployment
  labels:
    app: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
      - name: db
        image: santhoshparepu/postgres:taskmanager
        ports:
        - containerPort: 5432
      - name: endpoint
        image: santhoshparepu/endpoint:latest
        ports:
        - containerPort: 8000
      - name: scheduler
        image: santhoshparepu/scheduler:latest
---
apiVersion: v1
kind: Service
metadata:
  name: taskmanager
  namespace: default
  labels:
    application: taskmanager
spec:
  type: NodePort
  selector:
    application: taskmanager
  ports:
  - port: 8080
    targetPort: 8080
