version: '3'
services:
  db:
   image: dockerregistry.searchink.com:5000/postgres:taskmanager
   ports:
     - "5432:5432"
  web:
    image: dockerregistry.searchink.com:5000/endpoint:latest
    ports:
      - "8080:8080"
    depends_on:
      -  db
    environment:
      - DBHOST=db
  scheduler:
    image: dockerregistry.searchink.com:5000/scheduler:latest
    depends_on:
      - web
    environment:
      - DBHOST=db
